CREATE DATABASE work;

CREATE TABLE users (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KRY,
    username VARCHAR(30) NOT NULL,
    pass VARCHAR(30) NOT NULL,
    usertype INT(6) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
